services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
      - media-data:/app/media
      - ./google_credentials.json:/app/google_credentials.json:ro
      - app-logs:/app/logs
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_credentials.json
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
         echo 'Waiting for database to be ready...'
         while ! python -c 'import MySQLdb; MySQLdb.connect(host=\"db\", user=\"${DB_USER}\", password=\"${DB_PASS}\", database=\"${DB_NAME}\")' 2>/dev/null; do
           echo 'Database not ready yet, waiting...'
           sleep 1
         done
         echo 'Database is ready!'
         
         python manage.py migrate &&
         python manage.py collectstatic --noinput &&
         uwsgi --socket :9000 --workers 4 --master --enable-threads --module app.wsgi"

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
      - 443:443  # Add HTTPS port
    volumes:
      - static-data:/vol/web
      - media-data:/vol/media
      - ./ssl:/etc/nginx/ssl # Mount SSL certificates

volumes:
  mysql-data:
  static-data:
  media-data:
  app-logs: