# Generated by Django 4.0.10 on 2025-04-05 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wireframeupload',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RemoveField(
            model_name='wireframeupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='wireframeupload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wireframeupload',
            name='generated_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wireframeupload',
            name='title',
            field=models.CharField(default='Untitled Wireframe', max_length=255),
        ),
        migrations.AddField(
            model_name='wireframeupload',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wireframeupload',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
